version: "3"

services:
    mongo:
        image: "mongo"
        container_name: "mongo-node-backend-users"
        restart: unless-stopped
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=passwort
        ports:
            - "27017:27017"
        volumes:
            - /home/mongodb/notes:/data/db
